title: Riya Chhikara # your name (or website title) here
logo: "/images/my_image.jpg?raw=true" # your photo (or logo) here
description: > # your text below (remove <br> elements if you don't need line breaks)
  <br>
  Data Science Trainer at LSE Digital Skills Lab, with a master's degree in Data Science from London School of Economics. Previously data consultant with 2+ years of commercial experience in analytics and decision making (Infrastructure & Mining sector). 
  <br><br>
  Currently contributing to open source AI models.
  <br><br>
  <a href="https://www.linkedin.com/in/riya-chhikara/">View My LinkedIn Profile</a> 
  
theme: jekyll-theme-minimal
google_analytics: UA-000000-0 # your Google Analytics tracking ID here

colors:
  crimson: '#900C3F'
